name: Hourly Scanner

on:
  # schedule:
  #   - cron: '0,15,30,45 * * * *'  # every 15 minutes UTC

  workflow_dispatch:

permissions:
  contents: write   # required for pushing changes

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4   # v4 is the latest

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run Scanner
      run: python StochasticBuySell.py
      env:
        TELEGRAM_BOT_TOKEN_21_EMA: ${{ secrets.TELEGRAM_BOT_TOKEN_21_EMA }}
        TELEGRAM_CHAT_ID_21_EMA: ${{ secrets.TELEGRAM_CHAT_ID_21_EMA }}

